/**
 * Umiack Slider - Professional Edition (v4.0)
 * Multi-slider support with auto-generated DOM.
 * HTML only requires: <div class="umiack-slider-wrap" data-tour="xxx" data-slider="yyy"></div>
 * All internal elements (slides, buttons, dots, modal) are generated by JS.
 */
(function () {
  'use strict';

  // Prevent multiple initializations
  if (window.UmiackSliderInitialized) return;

  const slugify = (text) => {
    return text
      .toString()
      .toLowerCase()
      .trim()
      .replace(/[\s_]+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
      .replace(/-+/g, '-')
      .replace(/^-+/, '')
      .replace(/-+$/, '');
  };

  // SVG icon templates
  const SVG_PREV = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>';
  const SVG_NEXT = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>';
  const SVG_EXPAND = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3" /></svg>';
  const SVG_CLOSE = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>';

  /**
   * Build the inner DOM for a slider wrap element.
   * If the wrap already contains a .umiack-slider, skip (backward compat).
   */
  function buildSliderDOM(wrap) {
    if (wrap.querySelector('.umiack-slider')) return; // Already has structure

    wrap.innerHTML = '';

    const slider = document.createElement('div');
    slider.className = 'umiack-slider';

    const slides = document.createElement('div');
    slides.className = 'umiack-slides';
    slider.appendChild(slides);

    const btnPrev = document.createElement('button');
    btnPrev.className = 'umiack-btn umiack-btn-prev';
    btnPrev.setAttribute('aria-label', '前の写真');
    btnPrev.innerHTML = SVG_PREV;
    slider.appendChild(btnPrev);

    const btnNext = document.createElement('button');
    btnNext.className = 'umiack-btn umiack-btn-next';
    btnNext.setAttribute('aria-label', '次の写真');
    btnNext.innerHTML = SVG_NEXT;
    slider.appendChild(btnNext);

    const btnExpand = document.createElement('button');
    btnExpand.className = 'umiack-btn umiack-btn-expand';
    btnExpand.setAttribute('aria-label', 'フルスクリーンで見る');
    btnExpand.innerHTML = SVG_EXPAND;
    slider.appendChild(btnExpand);

    wrap.appendChild(slider);

    const dots = document.createElement('div');
    dots.className = 'umiack-dots';
    dots.setAttribute('role', 'tablist');
    dots.setAttribute('aria-label', 'スライド一覧');
    wrap.appendChild(dots);
  }

  /**
   * Build the shared modal element if it doesn't exist yet.
   */
  function ensureModal() {
    let modal = document.getElementById('umiack-modal');
    if (modal) return modal;

    modal = document.createElement('div');
    modal.className = 'umiack-modal';
    modal.id = 'umiack-modal';
    modal.setAttribute('role', 'dialog');
    modal.setAttribute('aria-modal', 'true');
    modal.setAttribute('aria-hidden', 'true');
    modal.setAttribute('aria-label', '拡大写真ビューアー');

    modal.innerHTML = `
      <div class="umiack-modal-inner">
        <img class="umiack-modal-img" src="" alt="">
        <button class="umiack-btn umiack-modal-nav umiack-modal-prev" aria-label="前の写真">${SVG_PREV}</button>
        <button class="umiack-btn umiack-modal-nav umiack-modal-next" aria-label="次の写真">${SVG_NEXT}</button>
        <button class="umiack-btn umiack-btn-close" aria-label="閉じる">${SVG_CLOSE}</button>
        <div class="umiack-modal-counter" aria-live="polite"></div>
      </div>
    `;

    document.body.appendChild(modal);
    return modal;
  }

  const init = async () => {
    // --- 1. Find ALL sliders on the page ---
    const allWraps = document.querySelectorAll('.umiack-slider-wrap');
    if (allWraps.length === 0) return;

    // --- 2. Build DOM for each slider and ensure modal exists ---
    allWraps.forEach(buildSliderDOM);
    const MID = ensureModal();

    const modalImg = MID.querySelector('.umiack-modal-img');
    const modalPrev = MID.querySelector('.umiack-modal-prev');
    const modalNext = MID.querySelector('.umiack-modal-next');
    const modalClose = MID.querySelector('.umiack-btn-close');
    const modalCount = MID.querySelector('.umiack-modal-counter');

    // --- 3. Modal Shared State & Functions ---
    function updateModalUI(targetImages, currentIndex) {
      const totalCount = targetImages.length;
      const data = targetImages[currentIndex];
      modalImg.src = data.src;
      modalImg.alt = data.alt;

      if (data.srcset) {
        modalImg.setAttribute('srcset', data.srcset);
        modalImg.setAttribute('sizes', '95vw');
      } else {
        modalImg.removeAttribute('srcset');
        modalImg.removeAttribute('sizes');
      }
      modalCount.textContent = `${currentIndex + 1} / ${totalCount}`;

      if (totalCount > 1) {
        modalPrev.style.display = 'flex';
        modalNext.style.display = 'flex';
      } else {
        modalPrev.style.display = 'none';
        modalNext.style.display = 'none';
      }

      window.modalGalleryState = {
        images: targetImages,
        current: currentIndex
      };
    }

    function moveModal(idx) {
      if (!window.modalGalleryState) return;
      const { images: targetImages } = window.modalGalleryState;
      const totalCount = targetImages.length;
      const nextIdx = (idx + totalCount) % totalCount;

      modalImg.style.transition = '';
      modalImg.style.transform = '';
      updateModalUI(targetImages, nextIdx);
    }

    // --- 4. Initialize each slider independently ---
    const sliderStates = [];

    for (let si = 0; si < allWraps.length; si++) {
      const WID = allWraps[si];

      // Skip already-initialized sliders
      if (WID.classList.contains('umiack-initialized')) continue;
      WID.classList.add('umiack-initialized');

      const track = WID.querySelector('.umiack-slides');
      const dotsWrap = WID.querySelector('.umiack-dots');
      const btnPrev = WID.querySelector('.umiack-btn-prev');
      const btnNext = WID.querySelector('.umiack-btn-next');
      const btnExp = WID.querySelector('.umiack-btn-expand');

      if (!track) continue;

      // Per-slider state
      const state = {
        total: 0,
        current: 0,
        images: [],
        WID: WID,
        track: track
      };
      sliderStates.push(state);

      // --- Build manifest URL ---
      const rawTourId = WID.getAttribute('data-tour');
      const rawSliderId = WID.getAttribute('data-slider');
      const tourId = rawTourId ? slugify(rawTourId) : null;

      if (tourId) {
        let manifestUrl;
        if (rawSliderId) {
          manifestUrl = `/common/umiack-site-assets/img/tours/${tourId}/${rawSliderId}/images-manifest.json`;
        } else {
          manifestUrl = `/common/umiack-site-assets/img/tours/${tourId}/images-manifest.json`;
        }

        try {
          const response = await fetch(manifestUrl);
          if (response.ok) {
            const manifest = await response.json();
            renderSlider(manifest, state, track);
          } else {
            console.warn(`Umiack Slider [${tourId}/${rawSliderId || 'root'}]: Manifest not found (${response.status}).`);
            scanHTML(state, WID, track);
          }
        } catch (err) {
          console.error(`Umiack Slider [${tourId}]: Error loading manifest:`, err);
          scanHTML(state, WID, track);
        }
      } else {
        scanHTML(state, WID, track);
      }

      finalizeSlider(state, WID, track, dotsWrap, btnPrev, btnNext, btnExp);
    }

    function scanHTML(state, WID, track) {
      const slideEls = WID.querySelectorAll('.umiack-slide');
      slideEls.forEach((el) => {
        const img = el.querySelector('img');
        const src = (img && (img.getAttribute('data-src') || img.src)) || '';
        const alt = (img && img.alt) || '';
        const srcset = img && img.getAttribute('srcset');
        state.images.push({ src, alt, srcset });
      });
    }

    function renderSlider(manifest, state, track) {
      track.innerHTML = '';
      manifest.forEach((item) => {
        const figure = document.createElement('figure');
        figure.className = 'umiack-slide';

        const img = document.createElement('img');

        const srcset = item.variants.map(v => `${v.webp} ${v.width}w`).join(', ');
        const fallbackSrc = item.variants.length > 0 ? item.variants[Math.min(1, item.variants.length - 1)].jpg : '';

        img.src = fallbackSrc;
        img.alt = item.alt;
        img.loading = 'lazy';
        img.setAttribute('srcset', srcset);
        img.setAttribute('sizes', '(min-width: 860px) 840px, 100vw');

        figure.appendChild(img);
        track.appendChild(figure);

        state.images.push({ src: fallbackSrc, alt: item.alt, srcset });
      });
    }

    function finalizeSlider(state, WID, track, dotsWrap, btnPrev, btnNext, btnExp) {
      state.total = state.images.length;
      if (state.total === 0) return;

      // Generate Dots
      if (dotsWrap) {
        dotsWrap.innerHTML = '';
        state.images.forEach((_, idx) => {
          const dot = document.createElement('button');
          dot.className = `umiack-dot${idx === 0 ? ' active' : ''}`;
          dot.setAttribute('aria-label', `Go to slide ${idx + 1}`);
          dot.addEventListener('click', () => goTo(state, idx, track, dotsWrap, WID));
          dotsWrap.appendChild(dot);
        });
      }

      // Navigation Setup
      if (btnPrev) btnPrev.addEventListener('click', () => goTo(state, state.current - 1, track, dotsWrap, WID));
      if (btnNext) btnNext.addEventListener('click', () => goTo(state, state.current + 1, track, dotsWrap, WID));

      // Expand button → opens modal with THIS slider's images
      if (btnExp) {
        btnExp.addEventListener('click', () => {
          if (state.images.length === 0) return;
          MID.classList.add('open');
          document.body.style.overflow = 'hidden';
          updateModalUI(state.images, state.current);
        });
      }

      // Touch swiping for this slider
      let startX = 0, startY = 0, diffX = 0, diffY = 0, isSwiping = false, startWidth = 0;

      track.addEventListener('touchstart', (e) => {
        startX = e.touches[0].clientX;
        startY = e.touches[0].clientY;
        isSwiping = false;
        startWidth = WID.offsetWidth;
        track.style.transition = 'none';
      }, { passive: false });

      track.addEventListener('touchmove', (e) => {
        diffX = e.touches[0].clientX - startX;
        diffY = e.touches[0].clientY - startY;

        if (Math.abs(diffX) > Math.abs(diffY)) {
          if (e.cancelable) e.preventDefault();
          isSwiping = true;
          const move = -(state.current * startWidth) + diffX;
          track.style.transform = `translate3d(${move}px, 0, 0)`;
        }
      }, { passive: false });

      track.addEventListener('touchend', () => {
        if (!isSwiping) return;
        track.style.transition = '';
        if (Math.abs(diffX) > 50) {
          diffX < 0 ? goTo(state, state.current + 1, track, dotsWrap, WID) : goTo(state, state.current - 1, track, dotsWrap, WID);
        } else {
          goTo(state, state.current, track, dotsWrap, WID);
        }
      });

      // Handle Resize (Debounced)
      let resizeTimer;
      window.addEventListener('resize', () => {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(() => {
          adjustHeight(state, track, WID);
        }, 100);
      });

      // Initial position
      goTo(state, 0, track, dotsWrap, WID);
    }

    // --- 5. Navigation Control ---
    function adjustHeight(state, track, WID) {
      const slides = track.querySelectorAll('.umiack-slide');
      const activeSlide = slides[state.current];
      if (!activeSlide) return;

      const img = activeSlide.querySelector('img');
      if (!img) return;

      const updateHeight = () => {
        requestAnimationFrame(() => {
          const sliderContainer = WID.querySelector('.umiack-slider');
          if (sliderContainer) {
            sliderContainer.style.height = `${img.offsetHeight}px`;
          }
        });
      };

      if (img.complete) {
        updateHeight();
      } else {
        img.onload = updateHeight;
      }
    }

    function goTo(state, idx, track, dotsWrap, WID) {
      if (state.total === 0) return;
      state.current = (idx + state.total) % state.total;
      track.style.transition = '';
      track.style.transform = `translate3d(-${state.current * 100}%, 0, 0)`;

      if (dotsWrap) {
        const dots = dotsWrap.querySelectorAll('.umiack-dot');
        dots.forEach((dot, j) => {
          dot.classList.toggle('active', j === state.current);
        });
      }

      adjustHeight(state, track, WID);
    }

    // --- 6. GLOBAL LIGHTBOX (Ukiyo-e etc.) ---
    const lbElements = document.querySelectorAll('.umiack-lightbox');
    const galleries = {};

    lbElements.forEach(el => {
      const gid = el.getAttribute('data-gallery') || 'default';
      if (!galleries[gid]) galleries[gid] = [];

      const img = el.querySelector('img');
      const item = {
        src: el.getAttribute('data-full-src') || el.href || (img && img.src) || '',
        alt: (img && (img.alt || img.getAttribute('data-alt'))) || '',
        srcset: (img && img.getAttribute('srcset')) || null,
        el: el
      };

      const idxInGallery = galleries[gid].length;
      galleries[gid].push(item);

      el.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        MID.classList.add('open');
        document.body.style.overflow = 'hidden';
        updateModalUI(galleries[gid], idxInGallery);
      });

      if (el.tagName !== 'A') {
        el.style.cursor = 'pointer';
      }
    });

    // --- 7. Common Modal Controls ---
    modalClose.addEventListener('click', () => {
      MID.classList.remove('open');
      document.body.style.overflow = '';
      window.modalGalleryState = null;
    });

    modalPrev.addEventListener('click', () => {
      if (window.modalGalleryState) moveModal(window.modalGalleryState.current - 1);
    });
    modalNext.addEventListener('click', () => {
      if (window.modalGalleryState) moveModal(window.modalGalleryState.current + 1);
    });

    MID.addEventListener('click', (e) => {
      if (e.target === MID) {
        MID.classList.remove('open');
        document.body.style.overflow = '';
        window.modalGalleryState = null;
      }
    });

    // Modal Swiping
    let mStartX = 0, mStartY = 0, mDiffX = 0, mDiffY = 0, mIsSwiping = false;

    MID.addEventListener('touchstart', (e) => {
      mStartX = e.touches[0].clientX;
      mStartY = e.touches[0].clientY;
      mIsSwiping = false;
      modalImg.style.transition = 'none';
    }, { passive: false });

    MID.addEventListener('touchmove', (e) => {
      mDiffX = e.touches[0].clientX - mStartX;
      mDiffY = e.touches[0].clientY - mStartY;
      if (Math.abs(mDiffX) > Math.abs(mDiffY)) {
        if (e.cancelable) e.preventDefault();
        mIsSwiping = true;
        modalImg.style.transform = `translate3d(${mDiffX}px, 0, 0)`;
      }
    }, { passive: false });

    MID.addEventListener('touchend', () => {
      if (!mIsSwiping) return;
      modalImg.style.transition = '';
      if (Math.abs(mDiffX) > 60) {
        const dir = mDiffX < 0 ? 1 : -1;
        if (window.modalGalleryState) moveModal(window.modalGalleryState.current + dir);
      } else {
        modalImg.style.transform = 'translate3d(0, 0, 0)';
      }
    });

    // Keyboard Support
    document.addEventListener('keydown', (e) => {
      const isModalOpen = MID.classList.contains('open');
      if (isModalOpen) {
        if (e.key === 'ArrowLeft') {
          if (window.modalGalleryState) moveModal(window.modalGalleryState.current - 1);
        }
        if (e.key === 'ArrowRight') {
          if (window.modalGalleryState) moveModal(window.modalGalleryState.current + 1);
        }
        if (e.key === 'Escape') {
          MID.classList.remove('open');
          document.body.style.overflow = '';
          window.modalGalleryState = null;
        }
      } else if (sliderStates.length > 0) {
        const s = sliderStates[0];
        const w = s.WID;
        const t = s.track;
        const d = w.querySelector('.umiack-dots');
        if (e.key === 'ArrowLeft') goTo(s, s.current - 1, t, d, w);
        if (e.key === 'ArrowRight') goTo(s, s.current + 1, t, d, w);
      }
    });

    window.UmiackSliderInitialized = true;
  };

  // Immediate or deferred execution
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();